#! /bin/bash

cd `dirname $0`

arch="`arch`"
tag=
uid=
platform=
args=()

# Except on Darwin, adopt current UID by default.
if test "`uname`" != Darwin; then
    uid="`id -u`"
    if [ $uid -le 1000 ]; then uid=""; fi
fi

usage () {
    armtext=
    if test "$arch" = "arm64" -o "$arch" = "aarch64"; then
        armtext=" [-a|--arm] [-x|--x86-64] [-u UID]"
    fi
    echo "Usage: cs61-build-docker$armtext" 1>&2
    exit 1
}

while test "$#" -ne 0; do
    if test "$1" = "-a" -o "$1" = "--arm" -o "$1" = "--arm64"; then
        if test "`arch`" = "arm64" -o "`arch`" = "aarch64"; then
            platform=linux/arm64
            shift
        else
            echo "\`cs61-build-docker --arm\` only works on ARM64 hosts" 1>&2
            exit 1
        fi
    elif test "$1" = "-x" -o "$1" = "--x86-64" -o "$1" = "--x86_64" -o "$1" = "--amd64"; then
        platform=linux/amd64
        shift
    elif expr "$1" : "--progress=.*" "|" "$1" = "--no-cache" > /dev/null; then
        args+=( "$1" )
        shift
    elif test "$1" = "-u" -o "$1" = "--user"; then
        if expr "$2" : "[0-9][0-9]*$" >/dev/null; then
            uid="$2"
            shift 2
        else
            usage
        fi
    elif expr "$1" : "-u[0-9]*$" "|" "$1" : "--user=[0-9][0-9]*" >/dev/null; then
        uid="`echo "$1" | sed 's/^[^0-9]*//'`"
        shift
    elif test "$1" = "-t" -o "$1" = "--tag"; then
        if expr "$2" : "..*$" >/dev/null; then
            tag="$2"
            shift 2
        else
            usage
        fi
    elif expr "$1" : "-t..*$" "|" "$1" : "--tag=..*" >/dev/null; then
        tag="`echo "$1" | sed 's/^--tag=//;s/^-t//'`"
        shift
    else
        usage
    fi
done

if test -z "$platform" -a \( "$arch" = "arm64" -o "$arch" = "aarch64" \); then
    platform=linux/arm64
elif test -z "$platform"; then
    platform=linux/amd64
fi

if test -z "$tag" -a "$platform" = linux/arm64; then
    tag=cs61:arm64
elif test -z "$tag"; then
    tag=cs61:latest
fi

if test -n "$uid"; then
    args+=( --build-arg UID="$uid" )
fi

if test $platform = linux/arm64; then
    exec docker build -t "$tag" -f Dockerfile.arm64 --platform linux/arm64 ${args[@]} .
else
    exec docker build -t "$tag" -f Dockerfile --platform linux/amd64 ${args[@]} .
fi
